import type { Metadata } from 'next';

import PageLayout from '@/components/Layout';
import { fontSans } from '@/configs/fonts';
import { ThemeProvider } from '@/providers/theme';
import { Theme } from '@radix-ui/themes';
import { ServerThemeProvider } from '@wits/next-themes';

import '@/styles/globals.css';
import '@/styles/drawer.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ServerThemeProvider>
      <html lang="en" className={fontSans.className}>
        <head />
        <body>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
            <Theme>
              <PageLayout>{children}</PageLayout>
            </Theme>
          </ThemeProvider>
        </body>
      </html>
    </ServerThemeProvider>
  );
}
