on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run_ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - name: Cache npm packages
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ runner.os }}-
          npm-
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - name: Execute remote script
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 159.89.208.114
        username: web
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2288
        command_timeout: 30m
        script: | 
          ~/cicd/teeup-user.sh
