on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run_ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3

    - name: Cache npm packages
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ runner.os }}-
          npm-

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: yarn install
    - run: yarn build

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: "unnecessary"

    - name: Adding Known Hosts
      run: ssh-keyscan -p 2288 -H 159.89.208.114 >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      run: rsync -avz --delete --exclude-from=".github/workflows/rsync-excludes.txt" -e 'ssh -p 2288' . web@159.89.208.114:/var/www/prudential/teeup/dev/teeup-user
    
    - name: Execute remote script
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 159.89.208.114
        username: web
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2288
        command_timeout: 30m
        script: | 
          ~/cicd/teeup-user.sh
